### ISSUE TITLE
When I click on element having text "text" command not working

### ISSUE THREAD

**Issue by shanisko** [Shashikant86/bddfire#10]
Step in feature: When I click on element having text "/html/body/div[2]/div/div[4]/div/div[2]"

Does not automatically provide the step definitions as the other commands do:
10 scenarios (1 undefined, 9 passed)
72 steps (5 skipped, 1 undefined, 66 passed)
0m19.841s

You can implement step definitions for undefined steps with these snippets:

When(/^I click on element having text "([^"]*)"$/) do |arg1|
  pending # Write code here that turns the phrase above into concrete actions

**Comment by Shashikant86** [comment]
@shanisko Thanks a lot for reporting the issue. I managed to reproduce and hopefully fixed the issue. 
It seems like Cucumber has changed regular expression format recently. I have pushed new version of the gem bddfire 2.0.8. Please update bddfire gem by reinstalling it or  

                                  $ gem update bddfire 

Hope this should resolve the issue. Let me know if not

**Comment by shanisko** [comment]
Awesome! I will let you know on Monday if it worked.

Sarah

**Comment by shanisko** [comment]
Uninstalled 2.0.7 and installed 2.0.8 and receiving this: (When I attempt to run using bundle exec cucumber it asks for 2.0.7. When I run bundle install after installing 2.0.8 it seems to revert to 2.0.7 and I still get the same issues above.

Select gem to uninstall:
 1. bddfire-2.0.7
 2. bddfire-2.0.8
 3. All versions
> 1
Successfully uninstalled bddfire-2.0.7
greelys-iMac:BDD-Cucumber sarah.hanisko$ bundle exec cucumber
Could not find bddfire-2.0.7 in any of the sources
Run `bundle install` to install missing gems.
greelys-iMac:BDD-Cucumber sarah.hanisko$ bundle exec cucumber
Could not find bddfire-2.0.7 in any of the sources
Run `bundle install` to install missing gems.
greelys-iMac:BDD-Cucumber sarah.hanisko$ gem uninstall bddfire
Remove executables:
	bddfire

in addition to the gem? [Yn]  y
Removing bddfire
Successfully uninstalled bddfire-2.0.8
greelys-iMac:BDD-Cucumber sarah.hanisko$ gem install bddfire
Fetching: bddfire-2.0.8.gem (100%)
======== Thanks for installing BDDfire. You can now perform Web, API, Mobile, Accessibility, Load Testing with single framework !!==================== 
Successfully installed bddfire-2.0.8
Parsing documentation for bddfire-2.0.8
Installing ri documentation for bddfire-2.0.8
Done installing documentation for bddfire after 0 seconds
1 gem installed
greelys-iMac:BDD-Cucumber sarah.hanisko$ cucumber
Could not find bddfire-2.0.7 in any of the sources
Run `bundle install` to install missing gems.
greelys-iMac:BDD-Cucumber sarah.hanisko$

**Comment by Shashikant86** [comment]
@shanisko It looks like you need to delete `Gemfile.lock` as bddfire version 2.0.7 is locked in that file. 

Try deleting `Gemfile.lock` and then do `bundle install` this should download new version of bddfire in the bundler. Now you can execute `bundle exec cucumber` 

I think that will fix it :)  Let me know i f not
